### ISSUE TITLE
Command Usage

### ISSUE THREAD

**Issue by synixebrett** [woofer808/indiCam#5]
Certain commands are considered broken or banned by many in the Arma community. Usually because they can cause instability or performance loss. The easiest way to remove all the `spawn`, `sleep`, and `waitUntil` would be to add a CBA dependency and use CBA per frame handlers since they are the preferred way of achieving the functionality indicam is trying to achieve.

`execVM` can and should be replaced as it would not require a CBA dependency.

**Banned**
`waitUntil` - 36 Uses
`execVM` - 32 Uses

**Avoid**
`spawn` - 101 Uses
`sleep` - 51 Uses

**Comment by woofer808** [comment]
Not necessarily the prettiest of code, but it's the style that's going to be used for indiCam in the foreseeable future, since that's what I know and where my comfort level is.
